require '__planetary-wars__.utils.lib.lib'

require 'prototypes.events'
require 'prototypes.entity'
require 'prototypes.friendly-colors'
require 'prototypes.map'
require 'prototypes.noise'
require 'prototypes.progression'
require 'prototypes.terrain'
require 'prototypes.triggers'
require 'prototypes.units'