return {
    auto_feed = {
        { name = 'automation-science-pack', count = 10 },
    },
    difficulty = {
        custom = { value = 0.00, color = { 255, 255, 255 } },
        itytd  = { value = 0.25, color = { 000, 255, 000 } },
        hand   = { value = 0.38, color = { 084, 255, 000 } },
        poc    = { value = 0.50, color = { 170, 255, 000 } },
        easy   = { value = 0.75, color = { 255, 255, 000 } },
        normal = { value = 1.00, color = { 255, 170, 000 } },
        hard   = { value = 2.00, color = { 255, 084, 000 } },
        fnf    = { value = 5.00, color = { 255, 000, 000 } },
    },
    force_names_map = {
        player = 'Spectator',
        north = 'North',
        south = 'South'
    },
    game_state = {
        initializing = 0,
        picking      = 1,
        preparing    = 2,
        playing      = 3,
        finished     = 4,
        resetting    = 5,
    },
    item_values = {
        ['automation-science-pack'] = { value = 0.0009, color = { 255, 050, 050 } },
        ['logistic-science-pack']   = { value = 0.0023, color = { 050, 255, 050 } },
        ['military-science-pack']   = { value = 0.0095, color = { 105, 105, 105 } },
        ['chemical-science-pack']   = { value = 0.0250, color = { 100, 200, 255 } },
        ['production-science-pack'] = { value = 0.1050, color = { 150, 025, 255 } },
        ['utility-science-pack']    = { value = 0.1680, color = { 210, 210, 060 } },
        ['space-science-pack']      = { value = 0.3500, color = { 255, 255, 255 } },
    },
    permission_group = {
        admin   = 'admin',
        default = 'default',
        jail    = 'jail',
        player  = 'player',
    },
    spawn_point = {
        player = { x = 0, y =   0 },
        north  = { x = 0, y = -90 },
        south  = { x = 0, y =  90 },
    },
    tags = {
        Referee    = { rank = 5, default = true, name = 'Referee',    sprite = 'info_no_border' },
        Captain    = { rank = 4, default = true, name = 'Captain',    sprite = 'virtual-signal/signal-star' },
        Custom     = { rank = 3, default = true, name = 'Custom',     sprite = 'item/coin' },
        Laser      = { rank = 2, default = true, name = 'Laser',      sprite = 'item/laser-turret' },
        Main       = { rank = 2, default = true, name = 'Main',       sprite = 'item/assembling-machine-2' },
        Nuclear    = { rank = 2, default = true, name = 'Nuclear',    sprite = 'item/nuclear-reactor' },
        Oil        = { rank = 2, default = true, name = 'Oil',        sprite = 'item/pumpjack' },
        Power      = { rank = 2, default = true, name = 'Power',      sprite = 'item/steam-engine' },
        Rocket     = { rank = 2, default = true, name = 'Rocket',     sprite = 'item/rocket-part' },
        Spam       = { rank = 2, default = true, name = 'Spam',       sprite = 'item/tank-cannon' },
        Support    = { rank = 2, default = true, name = 'Support',    sprite = 'item/electric-mining-drill' },
        Threatfarm = { rank = 2, default = true, name = 'Threatfarm', sprite = 'item/grenade' },
        Wall       = { rank = 2, default = true, name = 'Wall',       sprite = 'item/stone-wall' },
        East       = { rank = 1, default = true, name = 'East',       sprite = 'virtual-signal/signal-E' },
        West       = { rank = 1, default = true, name = 'West',       sprite = 'virtual-signal/signal-W' },
    },
    production = {
        'transport-belt',
        'underground-belt',
        'splitter',
        'fast-transport-belt',
        'fast-underground-belt',
        'fast-splitter',
        'inserter',
        'long-handed-inserter',
        'fast-inserter',
        'small-electric-pole',
        'medium-electric-pole',
        'big-electric-pole',
        'substation',
        'pipe',
        'pipe-to-ground',
        'car',
        'locomotive',
        'construction-robot',
        'roboport',
        'stone-brick',
        'concrete',
        'landfill',
        'boiler',
        'steam-engine',
        'solar-panel',
        'accumulator',
        'nuclear-reactor',
        'heat-pipe',
        'heat-exchanger',
        'steam-turbine',
        'electric-mining-drill',
        'offshore-pump',
        'pumpjack',
        'stone-furnace',
        'steel-furnace',
        'electric-furnace',
        'assembling-machine-1',
        'assembling-machine-2',
        'assembling-machine-3',
        'oil-refinery',
        'chemical-plant',
        'centrifuge',
        'beacon',
        'speed-module',
        'speed-module-2',
        'speed-module-3',
        'productivity-module',
        'productivity-module-2',
        'productivity-module-3',
        'satellite',
        'iron-plate',
        'copper-plate',
        'steel-plate',
        'plastic-bar',
        'sulfur',
        'battery',
        'explosives',
        'solid-fuel',
        'iron-gear-wheel',
        'copper-cable',
        'electronic-circuit',
        'advanced-circuit',
        'processing-unit',
        'engine-unit',
        'electric-engine-unit',
        'flying-robot-frame',
        'low-density-structure',
        'rocket-fuel',
        'uranium-238',
        'uranium-235',
        'automation-science-pack',
        'logistic-science-pack',
        'military-science-pack',
        'chemical-science-pack',
        'production-science-pack',
        'utility-science-pack',
        'space-science-pack',
        'firearm-magazine',
        'piercing-rounds-magazine',
        'cannon-shell',
        'explosive-cannon-shell',
        'rocket',
        'explosive-rocket',
        'grenade',
        'cluster-grenade',
        'poison-capsule',
        'slowdown-capsule',
        'defender-capsule',
        'stone-wall',
        'gun-turret',
        'laser-turret',
        'flamethrower-turret',
    }
}